# NumPy Notes
-------------

### 1. How to **import** NumPy

In [1]:
import numpy as np

### 2. In NumPy, array dimensions are called '*axes*'.

Example:

Coordinates of a point in 3D space are given by

```
[1, 2, 5].
```

Here, the array has 1 axis with a length of 3.

```
[[0, 3, 5],
[5, 5, 7]]
```

This array has 2 axes. One has a length of 3 and the other has a length of 2.

### 3. NumPy's array class is called **ndarray** (alias **array**)(numpy.array != array.array)

#### The more important attributes of an *ndarray* object are:

* ndarray.ndim

In [2]:
# Create an array of 15 elements in sequence starting from 0 and then reshape the array into a 3x5 matrix.
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.ndim # Shows the number of axes the ndarray has.

2

* ndarray.shape

In [5]:
a.shape # Shows the shape of the array in terms of the number of elements in each of its axes.

(3, 5)

* ndarray.size

In [6]:
a.size # Shows the total number of elements in the ndarray.

15

* ndarray.dtype

In [7]:
a.dtype # Shows the data type of the elements contained in an ndarray.

dtype('int64')

In [8]:
a.dtype.name # A slight variation.
# Shows only the name of the data type of the elements contained in an ndarray.

'int64'

* ndarray.itemsize

In [9]:
a.itemsize # Shows the size in bytes of each element of an ndarray.

8

In [10]:
a.dtype.itemsize # A slight variation.
# Shows the size in bytes of each element of an ndarray.

8

In [11]:
a.data # Shows the buffer containing the actual elements of an ndarray.

#### One more important function which is part of Python and not NumPy:

```
type()
```

Example:

In [12]:
type(a)

numpy.ndarray

### 4. Array creation

One method is to create an ndarray from a Python array as follow:

In [13]:
array0 = np.array([1, 2, 3, 4, 5])

In [14]:
print(array0)

[1 2 3 4 5]


In [15]:
type(array0)

numpy.ndarray

In [16]:
array1 = np.array([1.7, 4.4, 5.2, 9.1])

In [17]:
print(array1)

[1.7 4.4 5.2 9.1]


In [18]:
array1.dtype

dtype('float64')

A frequent error consists in calling `array` with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [19]:
array2 = np.array(1, 2, 3) # Wrong!

ValueError: only 2 non-keyword arguments accepted

In [ ]:
array3 = np.array(['a', 'b', 'c', 'd', 'e'])

In [ ]:
print(array3)

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays.

In [ ]:
array4 = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])

In [ ]:
print(array4)

In [ ]:
array5 = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

In [ ]:
print(array5)

In [ ]:
# You can also mention the data type.
array6 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype = complex)

In [ ]:
print(array6)

Some functions which create arrays with specific type of elements:

* `zeros`

In [20]:
array7 = np.zeros( (5, 6) )

In [21]:
print(array7)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


* `ones`

In [22]:
array8 = np.ones( (3, 4, 6), dtype = np.int32 ) # Data type can be specified too.

In [23]:
print(array8)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


In [24]:
array8.dtype

dtype('int32')

In [25]:
array8.itemsize

4

* `empty`

In [26]:
array9 = np.empty( (2, 3) ) # Uninitialized, output may vary.
print(array9)

[[5.79348556e+170 2.62241498e+180 5.44399525e-062]
 [1.42417251e+160 2.16385138e+190 8.20984545e-067]]


NumPy provides a function analogous to `range` (in Python) to create sequences of numbers.

In [27]:
array10 = np.arange( 0, 100, 5 )

In [28]:
print(array10)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [29]:
array11 = np.arange( 0, 3, 0.11 )

In [30]:
print(array11)

[0.   0.11 0.22 0.33 0.44 0.55 0.66 0.77 0.88 0.99 1.1  1.21 1.32 1.43
 1.54 1.65 1.76 1.87 1.98 2.09 2.2  2.31 2.42 2.53 2.64 2.75 2.86 2.97]


When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, NumPy provides a function called `linspace`

In [31]:
from numpy import pi

In [32]:
array12 = np.linspace( 0, 2, 100 ) # 100 elements from 0 to 2.

In [33]:
print(array12)

[0.         0.02020202 0.04040404 0.06060606 0.08080808 0.1010101
 0.12121212 0.14141414 0.16161616 0.18181818 0.2020202  0.22222222
 0.24242424 0.26262626 0.28282828 0.3030303  0.32323232 0.34343434
 0.36363636 0.38383838 0.4040404  0.42424242 0.44444444 0.46464646
 0.48484848 0.50505051 0.52525253 0.54545455 0.56565657 0.58585859
 0.60606061 0.62626263 0.64646465 0.66666667 0.68686869 0.70707071
 0.72727273 0.74747475 0.76767677 0.78787879 0.80808081 0.82828283
 0.84848485 0.86868687 0.88888889 0.90909091 0.92929293 0.94949495
 0.96969697 0.98989899 1.01010101 1.03030303 1.05050505 1.07070707
 1.09090909 1.11111111 1.13131313 1.15151515 1.17171717 1.19191919
 1.21212121 1.23232323 1.25252525 1.27272727 1.29292929 1.31313131
 1.33333333 1.35353535 1.37373737 1.39393939 1.41414141 1.43434343
 1.45454545 1.47474747 1.49494949 1.51515152 1.53535354 1.55555556
 1.57575758 1.5959596  1.61616162 1.63636364 1.65656566 1.67676768
 1.6969697  1.71717172 1.73737374 1.75757576 1.77777778 1.79797

`linspace` can be useful when we want to evaluate a mathematical function for a large number of points.

In [34]:
array13 = np.linspace( 0, 2 * pi, 100 )
function_for_many_points = np.sin(array13)

In [35]:
print(array13)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [36]:
print(function_for_many_points)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769